name: checks

on:
  workflow_call:

jobs:
  checks:
    name: Running checks
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setting up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9.13
          cache: true
          architecture: x64
          prerelease: true
          enable-pep582: true

      - name: Installing dependencies
        run: pdm install

      - name: Import checking using isort
        run: pdm run isort --check-only --diff powerfactory_utils tests

      - name: Code format checking using black
        run: pdm run black powerfactory_utils --check

      - name: Code checking using flake8
        run: pdm run flake518 powerfactory_utils

      - name: Type checking using mypy
        run: pdm run mypy powerfactory_utils
