name: checks

on:
  workflow_call:

jobs:
  checks:
    name: Running checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: cache-cargo-bin
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin

      - id: cache-uv-python
        uses: actions/cache@v4.0.2
        with:
          path: ~/.local/share/uv
          key: ${{ runner.os }}-uv-python-${{ matrix.python-version }}

      - name: Install uv
        if: steps.cache-cargo-bin.outputs.cache-hit != 'true'
        run: |
          curl -LsSf https://github.com/astral-sh/uv/releases/download/0.3.1/uv-installer.sh | sh

      - name: Install dependencies
        run: uv venv --python ${{ matrix.python-version }} && uv sync

      - name: Check code
        run: uv run ruff check .

      - name: Check code format
        run: uv run ruff format --check .

      - name: Type check using mypy
        run: uv run mypy .
