name: checks

on:
  workflow_call:

jobs:
  checks:
    name: Running checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up rye
        uses: eifinger/setup-rye@v4.2.1
        id: setup-rye

      - name: Pin python-version @ ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}

      - name: Install dependencies
        run: rye sync

      - name: Check code
        run: rye run ruff check .

      - name: Check code format
        run: rye run ruff format --check .

      - name: Type check using mypy
        run: rye run mypy .
