name: Draft PDF
on:
    push:
        paths:
        - docs/paper/**
        - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@85a18372e48f551d8af9ddb7a747de685fbbb01c  # master from 17.07.2024
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: docs/paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled PDF. 
          # Note, this should be the same directory as the input paper.md.
          path: docs/paper/joss_paper.pdf

