name: Test code

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yml
  test-code:
    name: Test code
    runs-on: ubuntu-latest
    needs: [check-code]
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache the default location where Cargo installs the binaries for Rust tools (uv) and dependencies
        id: cache-cargo-bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      
      - name: Install uv and set the python version
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.28"  # install a specific version of uv
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: uv venv --python ${{ matrix.python-version }} && uv sync

      - name: Unit test using pytest ${{ matrix.python-version }}
        run: uv run pytest